--O CLIENTE "Thiago Andrade Fiuza", ANTES MORADOR DA CIDADE DE ITAMBACURI, MUDOU DE ENDEREÇO 
--E SOLICITOU A ALTERÇÃO DE SEUS DADOS NO BANCO. O NOVO ENDEREÇO PASSA A SER NA CIDADE DE 
--UBERLANDIA, À AVENIDA AFONSO PENA. ATUALIZE OS DADOS DO CLIENTE:

--ANTES
SELECT * FROM CLIENTE WHERE CIDADE_CLIENTE = 'Itambacuri';

UPDATE CLIENTE SET CIDADE_CLIENTE = 'Uberlandia', 
		   RUA_CLIENTE='Avenida Afonso Pena'
WHERE 	NOME_CLIENTE = 'Thiago Andrade Fiuza' 
AND 	CIDADE_CLIENTE = 'Itambacuri';

--DEPOIS
SELECT * FROM CLIENTE WHERE CIDADE_CLIENTE = 'Uberlandia';

--AO FINAL DO MÊS É NECESSÁRIO ATUALIZAR O SALDO DAS CONTAS DOS CLIENTES APLICANDO
--A CORREÇÃO DA INFLAÇÃO DE 1% SOBRE AS MESMAS. IMPLEMENTE ESTA ATUALIZAÇÃO VIA SQL.

--ANTES E DEPOIS
SELECT NOME_CLIENTE, SUM(saldo_deposito) FROM DEPOSITO 
GROUP BY NOME_CLIENTE ORDER BY SUM(saldo_deposito);

UPDATE DEPOSITO SET SALDO_DEPOSITO = saldo_deposito * 1.01;

--AO FINAL DO MÊS É NECESSÁRIO ATUALIZAR O SALDO DAS CONTAS DOS CLIENTES APLICANDO
--OS JUROS DOS INVESTIMENTOS SOBRE AS MESMAS. 
--CLIENTES COM SALDO ATÉ DEZ MIL RECEBEM 3% DE ACRÉSCIMO.
--CLIENTES COM SALDO MAIOR QUE DEZ MIL RECEBEM 5% DE ACRÉSCIMO.

--ANTES E DEPOIS
SELECT nome_cliente, SUM(saldo_deposito) FROM DEPOSITO 
GROUP BY nome_cliente ORDER BY SUM(saldo_deposito);

UPDATE deposito SET SALDO_DEPOSITO = saldo_deposito * 1.03
WHERE saldo_deposito <= 10000;

UPDATE deposito SET SALDO_DEPOSITO =  * 1.05
WHERE saldo_deposito > 10000;

--A ORDEM DE EXECUÇÃO DAS CONSULTAS É IMPORTANTE PORQUE SENÃO UM 
--CLIENTE COM SALDO LIGEIRAMENTE INFERIOR A DEZ MIL PODE RECEBER 
--UM ACRÉSCIMO DE 8.15% = (1.03*1.05)


--INSERIR NOVOS DEPOSITOS NO BANCO DE DADOS
select * from deposito

INSERT INTO DEPOSITO
VALUES (10000, 20000,  'PUC', 'Carlos Eduardo', 1200);

--INCLUIR PARA TODOS OS CLIENTES COM EMPRESTIMOS NA AGENCIA PUC
--UMA CONTA DE DEPÓSITO NO VALOR DE R$ 200,00.

INSERT INTO DEPOSITO
SELECT NUMERO_EMPRESTIMO, NUMERO_CONTA, NOME_AGENCIA, NOME_CLIENTE, 200
FROM EMPRESTIMO WHERE NOME_AGENCIA = 'PUC';
